# Generated by Django 5.1.6 on 2025-02-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название блюда"),
                ),
                ("price", models.FloatField(verbose_name="Цена в руб.")),
            ],
            options={
                "verbose_name": "блюдо",
                "verbose_name_plural": "блюда",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(verbose_name="Номер стола"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAITING", "В ожидании"),
                            ("READY", "Готово"),
                            ("PAID", "Оплачено"),
                        ],
                        max_length=150,
                        null=True,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        help_text="необходимо выбрать хотя бы одно блюдо из списка доступных",
                        related_name="orders",
                        to="orders.dish",
                        verbose_name="список блюд",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
    ]
